Fix init_grouped_wgmma: revert to main branch setup_expert_weight_pointers
The previous commit reverted _forward_decode but forgot to also revert
init_grouped_wgmma, which was changed to build inplace WGMMA weight dicts
instead of calling setup_expert_weight_pointers. This caused
AttributeError: '_wgmma_weight_ptrs' not found at runtime.